name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 👈 allows manual runs via CLI/UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests beautifulsoup4

      - name: Run pipeline demo
        run: |
          export PYTHONPATH=src
          python -m permit_pipeline.main

      - name: Run tests
        run: |
          export PYTHONPATH=src
          pytest || echo "No tests yet"
